import Footer from "@/components/Footer";
import Header from "@/components/Header";
import AOSProvider from "@/components/AOSProvider";
import "aos/dist/aos.css";
import "../globals.css";


export const metadata = {
  title: "Yashik Yadav & Co",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }) {
  return (
    <>
      <Header />
      <AOSProvider>{children}</AOSProvider>
      <Footer />
    </>
  );
}
