import Footer from "@/components/Footer";
import Header from "@/components/Header";
import AOSProvider from "@/components/AOSProvider";
import "aos/dist/aos.css";
import "../globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Yashik Yadav & Co",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className={poppins.variable}>
      <Header />
      <AOSProvider>{children}</AOSProvider>
      <Footer />
    </main>
  );
}
